- src: https://github.com/freehck/ansible-role-disable-swap
  scm: git
  version: v1.0.1
  name: disable_swap

- src: https://github.com/geerlingguy/ansible-role-docker.git
  scm: git
  version: 6.0.3
  name: ansible-role-docker

- src: https://github.com/geerlingguy/ansible-role-containerd
  scm: git
  version: 1.3.0
  name: ansible-role-containerd