- name: Converge
  hosts:
    - control-plane
  module_defaults:
    # fixes issue with custom certificates if you work behind proxy:
    #   Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
    #
    # read more about module_defaults:
    #   https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html
    get_url:
      validate_certs: false
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  vars:
    docker_install_compose: false
  roles:
#     - { role: geerlingguy.docker }
    - { role: freehck.disable_swap }
    - { role: geerlingguy.containerd }
    - { role: andrewrothstein.etcd }
  tasks:
    - name: Install fish shell
      ansible.builtin.apt:
        name:
            - fish
            - less
            - vim
        state: latest

    - name: Configure fish as default shell
      ansible.builtin.user:
        name: "{{ ansible_facts['env']['USER'] }}"
        shell: /bin/fish

    - name: "Include mishavint.ansible_k8s_cluster"
      include_role:
        name: "mishavint.ansible_k8s_cluster"