---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: k8s-instance-01
    hostname: k8s-instance-01
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    groups: [control-plane]
    command: /sbin/init
    security_opts:
      - seccomp=unconfined
    # if you're using latest versions of ubuntu (22.04), check your default cgroup version.
    # command: stat -c %T -f /sys/fs/cgroup
    # if it is cgroup2fs, then change /etc/default/grub file, GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
    # update grub (sudo update-grub), reboot system to eplly changes
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:rw
     - /var/lib/containerd
     - /lib/modules:/lib/modules:ro
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    networks:
      - name: etcd_network
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy