---

- name: Update apt
  ansible.builtin.apt:
#     upgrade: yes
    update_cache: yes
    cache_valid_time: 86400  # One day

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Download Google Cloud public signing key
  ansible.builtin.apt_key:
    url: http://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add the Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes

- name: Update apt package index, install kubelet, kubeadm and kubectl
  ansible.builtin.apt:
    allow_unauthenticated: yes
    update_cache: yes
    name:
      - kubelet
      - kubeadm
      - kubectl

- name: Pin versions
  ansible.builtin.dpkg_selections:
    selection: hold
    name: "{{ item }}"
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Install etcd-client
  ansible.builtin.apt:
    name: etcd-client

- name: Add overlay and br_netfilter to modules-load.d/k8s.conf
  ansible.builtin.template:
   src: modules-load.d_k8s.conf
   dest: "/etc/modules-load.d/k8s.conf"

- name: Modprobe overlay and br_netfilter
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Forwarding IPv4 in sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: Install containerd
  ansible.builtin.apt:
    name:
      - containerd
      - containerd.io

- name: Delete config.toml file
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted