---

- name: Check Kubernetes API health
  block:
    - name: Query health endpoint to show output
      ansible.builtin.shell: |
        curl -k https://localhost:6443/livez?verbose 2>/dev/null
      register: curl_show

    - name: Debug
      ansible.builtin.debug:
        var: curl_show

    # https://kubernetes.io/docs/reference/using-api/health-checks/
    - name: Query health endpoint to count checks
      ansible.builtin.shell: |
        curl -k https://localhost:6443/livez?verbose 2>/dev/null | awk '/^\[/{print $NF}' | sort | uniq -c | wc -l
      register: curl
      changed_when: False

    - name: Debug
      ansible.builtin.debug:
        var: curl

    - name: API health is Ok
      ansible.builtin.assert:
        that: curl.stdout | int == 1

- name: Include kubelet
  ansible.builtin.include_tasks:
    file: ../verify-kubelet.yml
