---
- name: Converge
  hosts: all
  remote_user: mishavint
  become: yes
  roles:
    - { role: freehck.disable_swap }
    - { role: geerlingguy.docker }
    - { role: geerlingguy.containerd }
    - { role: andrewrothstein.etcd }
  tasks:
    - name: "Include mishavint.ansible_k8s_cluster"
      include_role:
        name: "mishavint.ansible_k8s_cluster"
