---
- name: Converge
  hosts: all
  become: yes
  roles:
    - { role: geerlingguy.docker }
  tasks:
    - name: "Include mishavint.ansible_k8s_cluster"
      include_role:
        name: "mishavint.ansible_k8s_cluster"
