---

- hosts: localhost
  connection: local
  pre_tasks:
    - name: Set proper nf_conntrack_max
      ansible.posix.sysctl:
        name: net.netfilter.nf_conntrack_max
        value: '393216'
        sysctl_set: true
        state: present
        reload: true

- hosts: all
  gather_facts: false
  tasks:
    - raw: apt update && apt install -y python3-pip python3 python3-apt

- name: Converge
  hosts: all
  become: yes
  become_method: su
  gather_facts: false
  vars:
    # geerlingguy.containerd related variables
    containerd_config_cgroup_driver_systemd: true
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
          - kmod  # modprobe and lsmod
          - net-tools
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  roles:
    - { role: andrewrothstein.etcd }
    - { role: ansible-etcd-cluster }
  tasks:
    - meta: flush_handlers

    - name: "Include cloud_labs.k8s_cluster"
      include_role:
        name: "cloud_labs.k8s_cluster"
