---
- name: Converge
  hosts: all
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  roles:
#    - { role: freehck.disable_swap }

#    - { role: geerlingguy.docker }
#    - { role: geerlingguy.containerd }
#    - { role: andrewrothstein.etcd }
#    - { role: ansible-etcd-cluster }
  tasks:
    - name: "Include cloud_labs.k8s_cluster"
      include_role:
        name: "cloud_labs.k8s_cluster"
